---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-back
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
{{ if .Values.prod }}
  replicas: {{ .Values.replicasProdBack }}
{{ else }}
  replicas: {{ .Values.replicasBack }}
{{ end }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.appPortBack }}
          name: backend
        env:
          - name: HTTP_PORT
            value: "{{ .Values.appPortBack }}"
          - name: DB_HOST
            value: "{{ .Chart.Name }}-db"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-back
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: backend
    port: {{ .Values.appPortBack }}
    protocol: TCP
