apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubernetes-01-prod-db
spec:
  selector:
    matchLabels:
      app: prod-db
  serviceName: kubernetes-01-prod-db
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgresql
        image: praqma/network-multitool
        ports:
        - containerPort: 5432
          name: postgresql
        env:
          - name: HTTP_PORT
            value: "5432"
          - name: HTTPS_PORT
            value: "8443"
