all:
  hosts:
    kube-cpl:
      ansible_host: 10.129.0.3
    kube-w01:
      ansible_host: 10.129.0.14
    kube-w02:
      ansible_host: 10.129.0.33
    kube-w03:
      ansible_host: 10.129.0.4
    kube-w04:
      ansible_host: 10.129.0.13
  children:
    kube_control_plane:
      hosts:
        kube-cpl:
    kube_node:
      hosts:
        kube-w01:
        kube-w02:
        kube-w03:
        kube-w04:
    etcd:
      hosts:
        kube-cpl:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
